#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(improper_ctypes)]
use crate::wrapper::vl53lx_platform_user_data::{VL53LX_Dev_t, VL53LX_DEV};
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

impl Default for VL53LX_LLDriverData_t {
    fn default() -> Self {
        Self {
            wArea1: [0; 1536],
            wArea2: [0; 512],
            wait_method: Default::default(),
            preset_mode: Default::default(),
            zone_preset: Default::default(),
            measurement_mode: Default::default(),
            offset_calibration_mode: Default::default(),
            offset_correction_mode: Default::default(),
            dmax_mode: Default::default(),
            phasecal_config_timeout_us: Default::default(),
            mm_config_timeout_us: Default::default(),
            range_config_timeout_us: Default::default(),
            inter_measurement_period_ms: Default::default(),
            dss_config__target_total_rate_mcps: Default::default(),
            fw_ready_poll_duration_ms: Default::default(),
            fw_ready: Default::default(),
            debug_mode: Default::default(),
            version: Default::default(),
            ll_state: Default::default(),
            gpio_interrupt_config: Default::default(),
            customer: Default::default(),
            cal_peak_rate_map: Default::default(),
            add_off_cal_data: Default::default(),
            fmt_dmax_cal: Default::default(),
            cust_dmax_cal: Default::default(),
            gain_cal: Default::default(),
            mm_roi: Default::default(),
            optical_centre: Default::default(),
            zone_cfg: Default::default(),
            tuning_parms: Default::default(),
            rtn_good_spads: Default::default(),
            refspadchar: Default::default(),
            ssc_cfg: Default::default(),
            histpostprocess: Default::default(),
            dmax_cfg: Default::default(),
            xtalk_extract_cfg: Default::default(),
            xtalk_cfg: Default::default(),
            offsetcal_cfg: Default::default(),
            zonecal_cfg: Default::default(),
            stat_nvm: Default::default(),
            hist_cfg: Default::default(),
            stat_cfg: Default::default(),
            gen_cfg: Default::default(),
            tim_cfg: Default::default(),
            dyn_cfg: Default::default(),
            sys_ctrl: Default::default(),
            sys_results: Default::default(),
            nvm_copy_data: Default::default(),
            hist_data: Default::default(),
            hist_xtalk: Default::default(),
            xtalk_shapes: Default::default(),
            xtalk_results: Default::default(),
            xtalk_cal: Default::default(),
            xtalk_extract: Default::default(),
            offset_results: Default::default(),
            core_results: Default::default(),
            dbg_results: Default::default(),
            smudge_correct_config: Default::default(),
            smudge_corrector_internals: Default::default(),
            low_power_auto_data: Default::default(),
            per_vcsel_cal_data: Default::default(),
            bin_rec_pos: Default::default(),
            pos_before_next_recom: Default::default(),
            multi_bins_rec: Default::default(),
            PreviousRangeMilliMeter: Default::default(),
            PreviousRangeStatus: Default::default(),
            PreviousExtendedRange: Default::default(),
            PreviousStreamCount: Default::default(),
        }
    }
}
